### ISSUE TITLE
Etape 3 : Création de l'espace commentaire

### ISSUE THREAD

**Issue by Ndl17** [Ndl17/P6SnowTricks#5]
**_Rappel de la demande:_**

Espace de discussion commun autour d’une figure
Les utilisateurs qui ne sont pas authentifiés peuvent consulter les discussions de toutes les figures. En revanche, ils ne peuvent pas poster de message.
Pour chaque message, il sera affiché les informations suivantes :

- le nom complet de l’auteur du message ;
- la photo de l’auteur du message ;
- la date de création du message ;
- le contenu du message.

Dans cet espace de discussion, on peut voir la liste des messages postés par les membres, du plus récent au plus ancien.
Ces messages doivent être paginés (10 par page).
Si l’utilisateur est authentifié, il peut voir un formulaire au-dessus de la liste avec un champs “message” qui est obligatoire. L’utilisateur peut poster autant de messages qu’il le souhaite.

**TODO:** 

- [x] Création d'une nouvelle entité comments
- [x] Création DataFixtures comments
- [x] Récupérer et afficher les commentaire en fonction de l'article
- [x] Mise en place formulaire création commentaire
- [x] Mise en forme CSS de la section commentaire

**Comment by Ndl17** [comment]
16 et 17/03 
Mise en place des commentaires dans la bdd et mise en place des fixtures

**Comment by Ndl17** [comment]
23 et 24/03
Finalisation des fixtures pour les commentaires.
Envoie des commentaires vers la vue détail de la figure en fonction de l'id de la figure concernée. Donc création pour cela d'une requête personnalisées dans commentRepository.

**Comment by Ndl17** [comment]
30 et 31/03:
mise en place formulaire d'ajout commentaire, redirection ajout commentaire
et rajout de la pagination sur 10 commentaires par page.

Restant à faire:
Mise en forme CSS de la section commentaire
revoir quelques redirections

**Comment by Ndl17** [comment]
6/04 
finalisation css mise en forme & verification redirections
